"""Add latitude, longitude, price_per_litre

Revision ID: 44fb2b6197cc
Revises: 
Create Date: 2025-09-22 08:26:07.947262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fb2b6197cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petrol_stations', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('petrol_stations', sa.Column('longitude', sa.Float(), nullable=False))
    op.alter_column('petrol_stations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('petrol_stations', 'price_per_litre',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_petrol_stations_name'), table_name='petrol_stations')
    op.drop_column('petrol_stations', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petrol_stations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_petrol_stations_name'), 'petrol_stations', ['name'], unique=False)
    op.alter_column('petrol_stations', 'price_per_litre',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('petrol_stations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('petrol_stations', 'longitude')
    op.drop_column('petrol_stations', 'latitude')
    # ### end Alembic commands ###
